on:
  workflow_call: 
    inputs:
        build-only:
            required: false
            default: false
            type: boolean
        image-id:
            required: false
            type: string
            default: "main-latest"
        namespace:
            required: true
            default: main
            type: string

name: _Build
env:
  IMAGE_ID: ${{ inputs.image-id }}
  NAMESPACE: ${{ inputs.namespace }}
  BUILD_ONLY: ${{ inputs.build-only }}

## dockerize by inputs

## build api
jobs:
  build_api:
    runs-on: ubuntu-latest

    # adding build
    steps:
      - name: "Checkout Github Action"
        uses: actions/setup-node@v4
      - name: restore api-dist
        uses: actions/cache@v4
        with:
          path: |
            api/dist
            api/test/dist
          key: ${{ env.IMAGE_ID }}-api-dist-${{ github.sha }}
          restore-keys: |
            ${{ env.IMAGE_ID }}-api-dist-
      - name: "Install Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - uses: "pnpm/action-setup@v3"
        name: Install pnpm
        id: pnpm-install
        with: 
          version: 10
          run_install: false

      - name: "install packages"
        run: |
          pnpm install

      - name: "build api"
        run: |
          echo "IMAGE_ID: ${{ env.IMAGE_ID }}"
          echo "NAMESPACE: ${{ env.NAMESPACE }}"
          echo "BUILD_ONLY: ${{ env.BUILD_ONLY }}"
      - name: Push
        run: |
          echo "IMAGE_ID: ${{ env.IMAGE_ID }}"