name: PR Build

on:
  pull_request:
    branches:
      - main
    types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
        - converted_to_draft


concurrency:
  group: ${{ github.workflow }}-PR-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.pull_request.draft == false }}
    name: Build
    uses: ./.github/workflows/_build-template.yml
    permissions:
      contents: read
      packages: write
    with:
      build-only: true
      namespace: main
      image-id: pr-${{ github.event.pull_request.number }}
    secrets: inherit