name: PR Build

on:
  pull_request:
    branches:
      - main
    types:
        - opened
        - synchronize
        - reopened
        - ready_for_review
        - converted_to_draft

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version